lib/recipex_web/router.ex
defmodule RecipexWeb.Router do
  use RecipexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RecipexWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RecipexWeb do
    pipe_through :browser

    get "/", RecipeController, :index
    resources "/recipes", RecipeController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", RecipexWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: RecipexWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/recipex/application.ex
defmodule Recipex.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      RecipexWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Recipex.PubSub},
      # Start the Endpoint (http/https)
      RecipexWeb.Endpoint
      # Start a worker by calling: Recipex.Worker.start_link(arg)
      # {Recipex.Worker, arg}
    ] ++ custom_workers(Mix.env)

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Recipex.Supervisor]
    app = Supervisor.start_link(children, opts)

    initialize_registry(Process.whereis(Recipex.Worker))

    app
  end

  def initialize_registry(nil), do: nil
  def initialize_registry(pid), do: Process.send_after(pid, :retrieve, 0)

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    RecipexWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  def custom_workers(:test), do: []

  def custom_workers(_env) do
    [
      {Registry, keys: :unique, name: Recipex.Registry},
      {Recipex.Worker, %{upsert_fun: &Recipex.Repo.upsert/1, retrieve_fun: &Recipex.Client.list_recipes/0}}
    ]
  end
end

lib/recipex/client.ex
defmodule Recipex.Client do
  @moduledoc """
  Executes a request to the contentful API to retrieve the recipe entries and
  uses the mapper to return a model
  """

  def list_recipes do
    build_url("/entries?sys.contentType.sys.id=recipe")
    |> HTTPoison.get!
    |> transform
  end

  def build_url(resource) do
    "https://cdn.contentful.com/spaces/#{space_id()}#{resource}&access_token=#{access_token()}"
  end

  defp transform(%HTTPoison.Response{body: body, status_code: 200}) do
    body
    |> Jason.decode!
    |> Recipex.Mapper.transform
  end

  defp space_id, do: config(:space_id)

  defp access_token, do: config(:access_token)

  defp config(attribute) do
    Keyword.get(Application.fetch_env!(:recipex, :contentful), attribute)
  end
end

lib/recipex/mailer.ex
defmodule Recipex.Mailer do
  use Swoosh.Mailer, otp_app: :recipex
end

lib/recipex/mapper.ex
defmodule Recipex.Mapper do
  @moduledoc """
  Converts a json into a model, the model in this case is %Recipex.Recipe
  """

  def transform(parsed_json) do
    parsed_json
    |> Map.get("items")
    |> Enum.map(fn item -> transform(item, parsed_json) end)
  end

  defp transform(node, fulljson) do
    %Recipex.Recipe{
      id: node["sys"]["id"],
      tags: Enum.map(node["fields"]["tags"] || [], fn item -> find_resource("tags", item, fulljson["includes"]["Entry"]) end),
      title: node["fields"]["title"],
      image: find_resource("photo", node["fields"]["photo"], fulljson["includes"]["Asset"]),
      chef_name: find_resource("chef", node["fields"]["chef"], fulljson["includes"]["Entry"]),
      description: node["fields"]["description"]
    }
  end

  defp find_resource(_, nil, _), do: nil
  defp find_resource("chef", %{"sys" => %{"id" => id}}, json) do
    Enum.find(json, fn x -> x["sys"]["id"] == id end)["fields"]["name"]
  end
  defp find_resource("tags", %{"sys" => %{"id" => id}}, json) do
    Enum.find(json, fn x -> x["sys"]["id"] == id end)["fields"]["name"]
  end
  defp find_resource("photo", %{"sys" => %{"id" => id}}, json) do
    Enum.find(json, fn x -> x["sys"]["id"] == id end)["fields"]["file"]["url"]
  end
end

lib/recipex/recipe.ex
defmodule Recipex.Recipe do
  @moduledoc """
  Represents the model for recipes
  """
  defstruct [:id, :title, :image, :tags, :description, :chef_name]
end

lib/recipex/repo.ex
defmodule Recipex.Repo do
  @moduledoc """
  Interfaces with the Registry acting as a repo
  """

  require Logger

  def upsert(%Recipex.Recipe{id: id} = model) do
    Registry.unregister(Recipex.Registry, id)
    Registry.register(Recipex.Registry, id, model)
  end

  def list_all do
    Registry.select(Recipex.Registry, [{{:"$1", :"$2", :"$3"}, [], [:"$3"]}])
  end

  def find(id) do
    case Registry.lookup(Recipex.Registry, id) do
      [{_, head} | _tail] -> head
      _ -> nil
    end
  end
end

lib/recipex/worker.ex
defmodule Recipex.Worker do
  @moduledoc """
  Updates the registry with new records when the cache expires
  """

  require Logger
  use GenServer

  def start_link(%{upsert_fun: _up_fn, retrieve_fun: _re_fn} = state) do
    GenServer.start_link(__MODULE__, state, name: __MODULE__)
  end

  @impl true
  def init(state) do
    schedule_work()

    {:ok, state}
  end

  @impl true
  def handle_info(:retrieve, %{upsert_fun: upsert_fun, retrieve_fun: retrieve_fun} = state) do
    schedule_work()

    Logger.info "Updating records on registry"
    Enum.each(retrieve_fun.(), fn item ->
      Logger.info "Updating record: #{item.id}"
      upsert_fun.(item)
    end)

    {:noreply, state}
  end


  defp schedule_work do
    Process.send_after(self(), :retrieve, interval())
  end

  defp interval do
    Application.fetch_env!(:recipex, :cache_expiration)
  end
end

lib/recipex_web/controllers/recipe_controller.ex
defmodule RecipexWeb.RecipeController do
  use RecipexWeb, :controller
  require Logger

  def index(conn, _params) do
    render(conn, "index.html", recipes: Recipex.Repo.list_all)
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", recipe: Recipex.Repo.find(id))
  end
end

lib/recipex_web/views/error_view.ex
defmodule RecipexWeb.ErrorView do
  use RecipexWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/recipex_web/views/layout_view.ex
defmodule RecipexWeb.LayoutView do
  use RecipexWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/recipex_web/views/page_view.ex
defmodule RecipexWeb.PageView do
  use RecipexWeb, :view
end

lib/recipex_web/views/recipe_view.ex
defmodule RecipexWeb.RecipeView do
  use RecipexWeb, :view

  def markdown_to_html(markdown) do
    Earmark.as_html!(markdown)
  end
end

lib/recipex_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/recipex_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/recipex_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Recipex", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/recipex_web/templates/page/index.html.heex
<section class="phx-hero">
  <section class="row">
    <article class="column">
      <h2>Resources</h2>
      <ul>
        <li>
          <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
        </li>
        <li>
          <a href="https://github.com/phoenixframework/phoenix">Source</a>
        </li>
        <li>
          <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
        </li>
      </ul>
    </article>
  </section>
</section>

lib/recipex_web/templates/recipe/index.html.heex
<section class="phx-hero">
    <h2>Recipes</h2>
    <ul>
      <%= for recipe <- assigns[:recipes] do %>
        <li>
          <a href={Routes.recipe_path(RecipexWeb.Endpoint, :show, recipe.id)}><%= recipe.title %></a>
          <img src={recipe.image} alt={recipe.title}/>
        </li>
      <% end %>
    </ul>
</section>

lib/recipex_web/templates/recipe/show.html.heex
<li>
  <a href={Routes.recipe_path(RecipexWeb.Endpoint, :index)}>Home</a>
</li>

<section class="phx-hero">
  <h1><%= assigns[:recipe].title %></h1>
  <img src={assigns[:recipe].image} alt={assigns[:recipe].title}/>

  <%= raw markdown_to_html(assigns[:recipe].description) %>

  <h3>Created by: <%= assigns[:recipe].chef_name%></h3>

  <h4>Tags</h4>
  <ul>
    <%= for tag <- assigns[:recipe].tags do %>
      <li>
        <span><%=tag%></span>
      </li>
    <% end %>
  </ul>
</section>